extends: default

ignore: |
  node_modules/
  pnpm-lock.yaml
  .github/workflows/*.yml

rules:
  document-start:
    present: false
  line-length:
    ignore: |
      /.github/actions/**/*.yml
      /.github/workflows/*.yml
      /.github/settings.yml
      /action.yml
      /.github/lint-pr.yaml
  truthy:
    ignore: |
      /.github/workflows/*.yml
      /.github/lint-pr.yaml
      /.github/workflows/pr-scope-laber.yaml
